version: "3"

services:

    mongodb:
        image: mongo
        ports:
            - "27020:27107"
        container_name: qboard_mongo
        restart: always
        networks:
            - mongo-network
            - python-network
    
    python:
        build:
            context: .
        command: python manage.py runserver
        ports: 
            - "8000:8000"
        volumes:
            - .:/code/
        networks: 
            - python-network
        environment: 
            - MONGO_URI=mongodb://asaha@eainfobiz.com:MongoDB@2020@mongodb-6953-0.cloudclusters.net:10001/Quark?authSource=admin
        container_name: qboard_python
        restart: always
        depends_on: 
            - mongodb
        links:
            - mongodb

networks: 
    python-network:
    mongo-network:
